= 31. Set up URL redirects to user docs
:page-pagination: sibling

In the output of the `pre-refresh-check` action, charm-refresh will display a URL to the charm's user documentation for in-place refreshes.
More info: xref:ROOT:user-experience.adoc[]

[#format]
== URL format

charm-refresh will generate the URL using this format:

----
https://charmhub.io/{charm_name}/docs/refresh/{charm_version}
----

`+{charm_name}+` will be replaced with the value of `charm_name` from xref:instantiate.adoc[].

// TODO link to charm code compatibility version
`+{charm_version}+` will be replaced with the charm compatibility version of the charm code that the `pre-refresh-check` action is run on (i.e. the charm code version that the user will be refreshing from).
The `/` character in the charm compatibility version will not be URL-encoded.

.Example URL
[subs="+attributes"]
----
https://charmhub.io/{ex-charm}/docs/refresh/{ex-charm-version}
----

[#target]
== Redirect target

This URL must be redirected to user documentation that provides instructions for how to refresh from this version (e.g. {ex-charm-version}) to all versions that support refreshing from that version.

NOTE: At the time this version (e.g. {ex-charm-version}) is released, it will not be possible to know all of the future versions that will support refreshing from that version

[#redirect]
== Set up redirects

[#community]
=== Community charm developers

xref:ROOT:contact.adoc[] and we will assist you with creating the redirects

[#canonical-staff]
=== Canonical staff

These instructions assume that all charm compatibility versions for a track share the same redirect target.
For more specific redirects (i.e. if the refresh instructions are different for some versions), refer to https://discourse.charmhub.io/t/content-cache-docs-sites-configuration/5408[IS' documentation on the sites.yaml format].

. Clone https://code.launchpad.net/canonical-mojo-specs

. Open `website-content-cache/production/sites.yaml`

. Under `charmhub.io` key -> `locations` key, add a redirect
+
--
.Example redirect
[.wrap,yaml,subs="+attributes"]
----
charmhub.io:
  locations:
    /{ex-charm}/docs/refresh/{ex-track}/: # <.>
      backend-inter-time: 5s
      cache-validity: '200 307 1h'
      extra-config: ['return 307 https://canonical-charmed-{ex-charm}.readthedocs-hosted.com/{ex-track}/how-to/refresh/'] # <.>
----
<.> Replace `{ex-charm}` with the charm name in metadata.yaml.
Replace `{ex-track}` with xref:charm-version.adoc#workflow[the track the charm is released to]
<.> Replace `https://canonical-charmed-{ex-charm}.readthedocs-hosted.com/{ex-track}/how-to/refresh/` with the <<target>>

NOTE: Use a https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/307[307 HTTP response status code] to indicate a temporary redirect so that the redirect target can be changed in the future (if versions in the same track need different refresh instructions)
--

. Commit changes
+
.Example commit message
----
Add Charmhub redirect for postgresql-k8s refresh user docs

Context: https://canonical-charm-refresh.readthedocs-hosted.com/latest/add-to-charm/user-docs-url/
{site-url}{page-url}
----
